/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.event.WindowEvent;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JSlider;
import simulacion.Calle;
import simulacion.Distribucion;
import simulacion.PuntosAcumulacion;
import simulacion.Ruta;

/**
 *
 * @author gtroncone
 */
public class MenuPuntosAcum extends javax.swing.JFrame {
    
    private final UI interfaz;
    
    private LinkedList<Ruta> rutas;
    private LinkedList<Calle> calles;
    
    private DefaultListModel modeloRutas;
    private DefaultListModel modeloCalles;
    
    private JSlider[] sliderDiario;
    private JSlider[] sliderSemanal;

    /**
     * Creates new form MenuPuntosAcum
     * @param ui
     */
    public MenuPuntosAcum(UI ui) {
        interfaz = ui;
        initComponents();
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.setResizable(false);
        
        modeloRutas = new DefaultListModel();
        listaRutas.setModel(modeloRutas);
        
        modeloCalles = new DefaultListModel();
        listaCalles.setModel(modeloCalles);
        
        rutas = interfaz.getSimulacion().getRutas();
        
        sliderDiario = new JSlider[24];
        sliderSemanal = new JSlider[7];
        
        sliderDiario[0] = slider12AM;
        sliderDiario[1] = slider1AM;
        sliderDiario[2] = slider2AM;
        sliderDiario[3] = slider3AM;
        sliderDiario[4] = slider4AM;
        sliderDiario[5] = slider5AM;
        sliderDiario[6] = slider6AM;
        sliderDiario[7] = slider7AM;
        sliderDiario[8] = slider8AM;
        sliderDiario[9] = slider9AM;
        sliderDiario[10] = slider10AM;
        sliderDiario[11] = slider11AM;
        sliderDiario[12] = slider12PM;
        sliderDiario[13] = slider1PM;
        sliderDiario[14] = slider2PM;
        sliderDiario[15] = slider3PM;
        sliderDiario[16] = slider4PM;
        sliderDiario[17] = slider5PM;
        sliderDiario[18] = slider6PM;
        sliderDiario[19] = slider7PM;
        sliderDiario[20] = slider8PM;
        sliderDiario[21] = slider9PM;
        sliderDiario[22] = slider10PM;
        sliderDiario[23] = slider11PM;
        
        sliderSemanal[0] = sliderLunes;
        sliderSemanal[1] = sliderMartes;
        sliderSemanal[2] = sliderMiercoles;
        sliderSemanal[3] = sliderJueves;
        sliderSemanal[4] = sliderViernes;
        sliderSemanal[5] = sliderSabado;
        sliderSemanal[6] = sliderDomingo;
    }
    
    public void setRutas(LinkedList<Ruta> rutas) {
        this.rutas = rutas;
        if (this.rutas != null) {
            modeloRutas.clear();
            for (int i = 0; i < this.rutas.size(); i++) {
                modeloRutas.addElement(this.rutas.get(i).getNombre());
            }
        }
        reiniciarMenu();
    }
    
    public void reiniciarMenu() {
        etiquetaNumPuntosAcum.setText("0");
        campoTasaAcum.setText("");
        campoTasaGen.setText("");
        for (int i = 0; i < sliderDiario.length; i++) {
            sliderDiario[i].setMaximum(200);
            sliderDiario[i].setValue(100);
            sliderDiario[i].setMinimum(0);
        }
        for (int i = 0; i < sliderSemanal.length; i++) {
            sliderSemanal[i].setMaximum(200);
            sliderSemanal[i].setValue(100);
            sliderSemanal[i].setMinimum(0);
        }
    }
    
    private boolean esValido() {
        if (!Distribucion.esDistValida(campoTasaAcum.getText(), false)) {
            UI.alerta("La notación de distribución en el campo de tasa de acumulación es incorrecta");
            return false;
        } else if (!Distribucion.esDistValida(campoTasaGen.getText(), true)) {
            UI.alerta("La notación de distribución en el campo de tasa de generación es incorrecta");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox8 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        tabsConfCiclos = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        etiquetaTasaAcum = new javax.swing.JLabel();
        campoTasaAcum = new javax.swing.JTextField();
        btnCrearPtoAcum = new javax.swing.JButton();
        btnEditarPtoAcum = new javax.swing.JButton();
        btnCancelarPtoAcum = new javax.swing.JButton();
        etiquetaTasaGen = new javax.swing.JLabel();
        campoTasaGen = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaRutas = new javax.swing.JList<>();
        etiquetaRutas = new javax.swing.JLabel();
        etiquetaCalles = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaCalles = new javax.swing.JList<>();
        etiquetaCantPuntosAcum = new javax.swing.JLabel();
        etiquetaNumPuntosAcum = new javax.swing.JLabel();
        btnNuevoPuntoAcum = new javax.swing.JButton();
        btnRestarPuntoAcum = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        etiquetaCicloDiario = new javax.swing.JLabel();
        etiquetaCicloSemanal = new javax.swing.JLabel();
        tabCicloDIario = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        slider12AM = new javax.swing.JSlider();
        etiqueta12AM = new javax.swing.JLabel();
        slider1AM = new javax.swing.JSlider();
        etiqueta1AM = new javax.swing.JLabel();
        etiqueta2AM = new javax.swing.JLabel();
        slider2AM = new javax.swing.JSlider();
        etiqueta3AM = new javax.swing.JLabel();
        slider3AM = new javax.swing.JSlider();
        slider4AM = new javax.swing.JSlider();
        etiqueta4AM = new javax.swing.JLabel();
        etiqueta5AM = new javax.swing.JLabel();
        slider5AM = new javax.swing.JSlider();
        jPanel9 = new javax.swing.JPanel();
        slider6AM = new javax.swing.JSlider();
        etiqueta6AM = new javax.swing.JLabel();
        etiqueta7AM = new javax.swing.JLabel();
        slider7AM = new javax.swing.JSlider();
        slider8AM = new javax.swing.JSlider();
        etiqueta8AM = new javax.swing.JLabel();
        etiqueta9AM = new javax.swing.JLabel();
        slider9AM = new javax.swing.JSlider();
        slider10AM = new javax.swing.JSlider();
        etiqueta10AM = new javax.swing.JLabel();
        slider11AM = new javax.swing.JSlider();
        etiqueta11AM = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        slider12PM = new javax.swing.JSlider();
        etiqueta12PM = new javax.swing.JLabel();
        etiqueta1PM = new javax.swing.JLabel();
        slider1PM = new javax.swing.JSlider();
        slider2PM = new javax.swing.JSlider();
        etiqueta2PM = new javax.swing.JLabel();
        etiqueta3PM = new javax.swing.JLabel();
        slider3PM = new javax.swing.JSlider();
        slider4PM = new javax.swing.JSlider();
        etiqueta4PM = new javax.swing.JLabel();
        slider5PM = new javax.swing.JSlider();
        etiqueta5PM = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        etiqueta6PM = new javax.swing.JLabel();
        slider6PM = new javax.swing.JSlider();
        etiqueta7PM = new javax.swing.JLabel();
        slider7PM = new javax.swing.JSlider();
        etiqueta8PM = new javax.swing.JLabel();
        slider8PM = new javax.swing.JSlider();
        etiqueta9PM = new javax.swing.JLabel();
        slider9PM = new javax.swing.JSlider();
        etiqueta10PM = new javax.swing.JLabel();
        slider10PM = new javax.swing.JSlider();
        etiqueta11PM = new javax.swing.JLabel();
        slider11PM = new javax.swing.JSlider();
        jPanel12 = new javax.swing.JPanel();
        etiquetaLunes = new javax.swing.JLabel();
        sliderLunes = new javax.swing.JSlider();
        etiquetaMartes = new javax.swing.JLabel();
        sliderMartes = new javax.swing.JSlider();
        etiquetaMiercoles = new javax.swing.JLabel();
        sliderMiercoles = new javax.swing.JSlider();
        etiquetaJueves = new javax.swing.JLabel();
        sliderJueves = new javax.swing.JSlider();
        etiquetaViernes = new javax.swing.JLabel();
        sliderViernes = new javax.swing.JSlider();
        etiquetaSabado = new javax.swing.JLabel();
        sliderSabado = new javax.swing.JSlider();
        sliderDomingo = new javax.swing.JSlider();
        etiquetaDoming = new javax.swing.JLabel();

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiquetaTasaAcum.setText("Tasa de Acumulación (Dist)");

        btnCrearPtoAcum.setText("Crear");
        btnCrearPtoAcum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPtoAcumActionPerformed(evt);
            }
        });

        btnEditarPtoAcum.setText("Editar");
        btnEditarPtoAcum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPtoAcumActionPerformed(evt);
            }
        });

        btnCancelarPtoAcum.setText("Cancelar");
        btnCancelarPtoAcum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPtoAcumActionPerformed(evt);
            }
        });

        etiquetaTasaGen.setText("Tasa de Generación (Dist)");

        listaRutas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaRutas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaRutasMouseClicked(evt);
            }
        });
        listaRutas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaRutasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaRutas);

        etiquetaRutas.setText("Rutas");

        etiquetaCalles.setText("Calles");

        listaCalles.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaCalles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaCallesMouseClicked(evt);
            }
        });
        listaCalles.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaCallesValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaCalles);

        etiquetaCantPuntosAcum.setText("Cantidad Puntos de Acum.");

        etiquetaNumPuntosAcum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaNumPuntosAcum.setText("0");

        btnNuevoPuntoAcum.setText("+");
        btnNuevoPuntoAcum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPuntoAcumActionPerformed(evt);
            }
        });

        btnRestarPuntoAcum.setText("-");
        btnRestarPuntoAcum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarPuntoAcumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnCrearPtoAcum, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(btnEditarPtoAcum, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarPtoAcum, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(etiquetaRutas)
                            .addComponent(etiquetaCalles)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiquetaTasaAcum)
                                    .addComponent(etiquetaTasaGen))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoTasaAcum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoTasaGen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(etiquetaCantPuntosAcum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(etiquetaNumPuntosAcum, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNuevoPuntoAcum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRestarPuntoAcum)))
                        .addGap(0, 15, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaRutas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(etiquetaCalles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCantPuntosAcum)
                    .addComponent(etiquetaNumPuntosAcum)
                    .addComponent(btnNuevoPuntoAcum)
                    .addComponent(btnRestarPuntoAcum))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTasaAcum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaTasaAcum))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaTasaGen)
                    .addComponent(campoTasaGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearPtoAcum)
                    .addComponent(btnEditarPtoAcum)
                    .addComponent(btnCancelarPtoAcum))
                .addGap(23, 23, 23))
        );

        tabsConfCiclos.addTab("Punto de Acumulación", jPanel1);

        jPanel3.setPreferredSize(new java.awt.Dimension(2000, 100));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2000, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        etiquetaCicloDiario.setText("Ciclo Diario");

        etiquetaCicloSemanal.setText("Ciclo Semanal");

        slider12AM.setMaximum(10);
        slider12AM.setMinimum(-10);
        slider12AM.setOrientation(javax.swing.JSlider.VERTICAL);
        slider12AM.setPaintLabels(true);
        slider12AM.setSnapToTicks(true);
        slider12AM.setValue(0);

        etiqueta12AM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta12AM.setText("12");

        slider1AM.setMaximum(10);
        slider1AM.setMinimum(-10);
        slider1AM.setOrientation(javax.swing.JSlider.VERTICAL);
        slider1AM.setPaintLabels(true);
        slider1AM.setSnapToTicks(true);
        slider1AM.setValue(0);

        etiqueta1AM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta1AM.setText("01");

        etiqueta2AM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta2AM.setText("02");

        slider2AM.setMaximum(10);
        slider2AM.setMinimum(-10);
        slider2AM.setOrientation(javax.swing.JSlider.VERTICAL);
        slider2AM.setPaintLabels(true);
        slider2AM.setSnapToTicks(true);
        slider2AM.setValue(0);

        etiqueta3AM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta3AM.setText("03");

        slider3AM.setMaximum(10);
        slider3AM.setMinimum(-10);
        slider3AM.setOrientation(javax.swing.JSlider.VERTICAL);
        slider3AM.setPaintLabels(true);
        slider3AM.setSnapToTicks(true);
        slider3AM.setValue(0);

        slider4AM.setMaximum(10);
        slider4AM.setMinimum(-10);
        slider4AM.setOrientation(javax.swing.JSlider.VERTICAL);
        slider4AM.setPaintLabels(true);
        slider4AM.setSnapToTicks(true);
        slider4AM.setValue(0);

        etiqueta4AM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta4AM.setText("04");

        etiqueta5AM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta5AM.setText("05");

        slider5AM.setMaximum(10);
        slider5AM.setMinimum(-10);
        slider5AM.setOrientation(javax.swing.JSlider.VERTICAL);
        slider5AM.setPaintLabels(true);
        slider5AM.setSnapToTicks(true);
        slider5AM.setValue(0);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slider12AM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiqueta12AM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slider1AM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiqueta1AM, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slider2AM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiqueta2AM, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slider3AM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiqueta3AM, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slider4AM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiqueta4AM, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slider5AM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiqueta5AM, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(etiqueta12AM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slider12AM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(etiqueta1AM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slider1AM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(etiqueta2AM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slider2AM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(etiqueta3AM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slider3AM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(etiqueta4AM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slider4AM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(etiqueta5AM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slider5AM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabCicloDIario.addTab("AM (12 - 5)", jPanel8);

        slider6AM.setMaximum(10);
        slider6AM.setMinimum(-10);
        slider6AM.setOrientation(javax.swing.JSlider.VERTICAL);
        slider6AM.setPaintLabels(true);
        slider6AM.setSnapToTicks(true);
        slider6AM.setValue(0);

        etiqueta6AM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta6AM.setText("06");

        etiqueta7AM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta7AM.setText("07");

        slider7AM.setMaximum(10);
        slider7AM.setMinimum(-10);
        slider7AM.setOrientation(javax.swing.JSlider.VERTICAL);
        slider7AM.setPaintLabels(true);
        slider7AM.setSnapToTicks(true);
        slider7AM.setValue(0);

        slider8AM.setMaximum(10);
        slider8AM.setMinimum(-10);
        slider8AM.setOrientation(javax.swing.JSlider.VERTICAL);
        slider8AM.setPaintLabels(true);
        slider8AM.setSnapToTicks(true);
        slider8AM.setValue(0);

        etiqueta8AM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta8AM.setText("08");

        etiqueta9AM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta9AM.setText("09");

        slider9AM.setMaximum(10);
        slider9AM.setMinimum(-10);
        slider9AM.setOrientation(javax.swing.JSlider.VERTICAL);
        slider9AM.setPaintLabels(true);
        slider9AM.setSnapToTicks(true);
        slider9AM.setValue(0);

        slider10AM.setMaximum(10);
        slider10AM.setMinimum(-10);
        slider10AM.setOrientation(javax.swing.JSlider.VERTICAL);
        slider10AM.setPaintLabels(true);
        slider10AM.setSnapToTicks(true);
        slider10AM.setValue(0);

        etiqueta10AM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta10AM.setText("10");

        slider11AM.setMaximum(10);
        slider11AM.setMinimum(-10);
        slider11AM.setOrientation(javax.swing.JSlider.VERTICAL);
        slider11AM.setPaintLabels(true);
        slider11AM.setSnapToTicks(true);
        slider11AM.setValue(0);

        etiqueta11AM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta11AM.setText("11");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slider6AM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiqueta6AM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slider7AM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiqueta7AM, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slider8AM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiqueta8AM, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slider9AM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiqueta9AM, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slider10AM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiqueta10AM, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slider11AM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiqueta11AM, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(etiqueta6AM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slider6AM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(etiqueta7AM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slider7AM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(etiqueta8AM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slider8AM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(etiqueta9AM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slider9AM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(etiqueta10AM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slider10AM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(etiqueta11AM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slider11AM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabCicloDIario.addTab("AM (6 - 11)", jPanel9);

        slider12PM.setMaximum(10);
        slider12PM.setMinimum(-10);
        slider12PM.setOrientation(javax.swing.JSlider.VERTICAL);
        slider12PM.setPaintLabels(true);
        slider12PM.setSnapToTicks(true);
        slider12PM.setValue(0);

        etiqueta12PM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta12PM.setText("12");

        etiqueta1PM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta1PM.setText("01");

        slider1PM.setMaximum(10);
        slider1PM.setMinimum(-10);
        slider1PM.setOrientation(javax.swing.JSlider.VERTICAL);
        slider1PM.setPaintLabels(true);
        slider1PM.setSnapToTicks(true);
        slider1PM.setValue(0);

        slider2PM.setMaximum(10);
        slider2PM.setMinimum(-10);
        slider2PM.setOrientation(javax.swing.JSlider.VERTICAL);
        slider2PM.setPaintLabels(true);
        slider2PM.setSnapToTicks(true);
        slider2PM.setValue(0);

        etiqueta2PM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta2PM.setText("02");

        etiqueta3PM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta3PM.setText("03");

        slider3PM.setMaximum(10);
        slider3PM.setMinimum(-10);
        slider3PM.setOrientation(javax.swing.JSlider.VERTICAL);
        slider3PM.setPaintLabels(true);
        slider3PM.setSnapToTicks(true);
        slider3PM.setValue(0);

        slider4PM.setMaximum(10);
        slider4PM.setMinimum(-10);
        slider4PM.setOrientation(javax.swing.JSlider.VERTICAL);
        slider4PM.setPaintLabels(true);
        slider4PM.setSnapToTicks(true);
        slider4PM.setValue(0);

        etiqueta4PM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta4PM.setText("04");

        slider5PM.setMaximum(10);
        slider5PM.setMinimum(-10);
        slider5PM.setOrientation(javax.swing.JSlider.VERTICAL);
        slider5PM.setPaintLabels(true);
        slider5PM.setSnapToTicks(true);
        slider5PM.setValue(0);

        etiqueta5PM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta5PM.setText("05");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slider12PM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiqueta12PM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slider1PM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiqueta1PM, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slider2PM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiqueta2PM, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slider3PM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiqueta3PM, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slider4PM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiqueta4PM, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slider5PM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiqueta5PM, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(etiqueta12PM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slider12PM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(etiqueta1PM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slider1PM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(etiqueta2PM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slider2PM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(etiqueta3PM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slider3PM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(etiqueta4PM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slider4PM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(etiqueta5PM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slider5PM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabCicloDIario.addTab("PM (12 - 5)", jPanel10);

        etiqueta6PM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta6PM.setText("06");

        slider6PM.setMaximum(10);
        slider6PM.setMinimum(-10);
        slider6PM.setOrientation(javax.swing.JSlider.VERTICAL);
        slider6PM.setPaintLabels(true);
        slider6PM.setSnapToTicks(true);
        slider6PM.setValue(0);

        etiqueta7PM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta7PM.setText("07");

        slider7PM.setMaximum(10);
        slider7PM.setMinimum(-10);
        slider7PM.setOrientation(javax.swing.JSlider.VERTICAL);
        slider7PM.setPaintLabels(true);
        slider7PM.setSnapToTicks(true);
        slider7PM.setValue(0);

        etiqueta8PM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta8PM.setText("08");

        slider8PM.setMaximum(10);
        slider8PM.setMinimum(-10);
        slider8PM.setOrientation(javax.swing.JSlider.VERTICAL);
        slider8PM.setPaintLabels(true);
        slider8PM.setSnapToTicks(true);
        slider8PM.setValue(0);

        etiqueta9PM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta9PM.setText("09");

        slider9PM.setMaximum(10);
        slider9PM.setMinimum(-10);
        slider9PM.setOrientation(javax.swing.JSlider.VERTICAL);
        slider9PM.setPaintLabels(true);
        slider9PM.setSnapToTicks(true);
        slider9PM.setValue(0);

        etiqueta10PM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta10PM.setText("10");

        slider10PM.setMaximum(10);
        slider10PM.setMinimum(-10);
        slider10PM.setOrientation(javax.swing.JSlider.VERTICAL);
        slider10PM.setPaintLabels(true);
        slider10PM.setSnapToTicks(true);
        slider10PM.setValue(0);

        etiqueta11PM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta11PM.setText("11");

        slider11PM.setMaximum(10);
        slider11PM.setMinimum(-10);
        slider11PM.setOrientation(javax.swing.JSlider.VERTICAL);
        slider11PM.setPaintLabels(true);
        slider11PM.setSnapToTicks(true);
        slider11PM.setValue(0);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slider6PM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiqueta6PM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slider7PM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiqueta7PM, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slider8PM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiqueta8PM, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slider9PM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiqueta9PM, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slider10PM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiqueta10PM, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slider11PM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiqueta11PM, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(etiqueta6PM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slider6PM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(etiqueta7PM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slider7PM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(etiqueta8PM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slider8PM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(etiqueta9PM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slider9PM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(etiqueta10PM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slider10PM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(etiqueta11PM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slider11PM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabCicloDIario.addTab("PM (6 - 11)", jPanel11);

        etiquetaLunes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaLunes.setText("Lunes");

        sliderLunes.setMaximum(10);
        sliderLunes.setMinimum(-10);
        sliderLunes.setOrientation(javax.swing.JSlider.VERTICAL);
        sliderLunes.setPaintLabels(true);
        sliderLunes.setSnapToTicks(true);
        sliderLunes.setValue(0);

        etiquetaMartes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaMartes.setText("Martes");

        sliderMartes.setMaximum(10);
        sliderMartes.setMinimum(-10);
        sliderMartes.setOrientation(javax.swing.JSlider.VERTICAL);
        sliderMartes.setPaintLabels(true);
        sliderMartes.setSnapToTicks(true);
        sliderMartes.setValue(0);

        etiquetaMiercoles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaMiercoles.setText("Miércoles");

        sliderMiercoles.setMaximum(10);
        sliderMiercoles.setMinimum(-10);
        sliderMiercoles.setOrientation(javax.swing.JSlider.VERTICAL);
        sliderMiercoles.setPaintLabels(true);
        sliderMiercoles.setSnapToTicks(true);
        sliderMiercoles.setValue(0);

        etiquetaJueves.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaJueves.setText("Jueves");

        sliderJueves.setMaximum(10);
        sliderJueves.setMinimum(-10);
        sliderJueves.setOrientation(javax.swing.JSlider.VERTICAL);
        sliderJueves.setPaintLabels(true);
        sliderJueves.setSnapToTicks(true);
        sliderJueves.setValue(0);

        etiquetaViernes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaViernes.setText("Viernes");

        sliderViernes.setMaximum(10);
        sliderViernes.setMinimum(-10);
        sliderViernes.setOrientation(javax.swing.JSlider.VERTICAL);
        sliderViernes.setPaintLabels(true);
        sliderViernes.setSnapToTicks(true);
        sliderViernes.setValue(0);

        etiquetaSabado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaSabado.setText("Sábado");

        sliderSabado.setMaximum(10);
        sliderSabado.setMinimum(-10);
        sliderSabado.setOrientation(javax.swing.JSlider.VERTICAL);
        sliderSabado.setPaintLabels(true);
        sliderSabado.setSnapToTicks(true);
        sliderSabado.setValue(0);

        sliderDomingo.setMaximum(10);
        sliderDomingo.setMinimum(-10);
        sliderDomingo.setOrientation(javax.swing.JSlider.VERTICAL);
        sliderDomingo.setPaintLabels(true);
        sliderDomingo.setSnapToTicks(true);
        sliderDomingo.setValue(0);

        etiquetaDoming.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaDoming.setText("Domingo");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sliderLunes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaLunes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sliderMartes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaMartes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sliderMiercoles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaMiercoles, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sliderJueves, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaJueves, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sliderViernes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaViernes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sliderSabado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaSabado, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderDomingo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaDoming, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(etiquetaLunes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sliderLunes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(etiquetaMartes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sliderMartes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(etiquetaMiercoles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sliderMiercoles, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(etiquetaJueves)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sliderJueves, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(etiquetaViernes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sliderViernes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaSabado)
                    .addComponent(etiquetaDoming))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sliderSabado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sliderDomingo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(etiquetaCicloDiario)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tabCicloDIario, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(etiquetaCicloSemanal)
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaCicloDiario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabCicloDIario, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(etiquetaCicloSemanal)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabsConfCiclos.addTab("Ciclos Diarios y Semanales", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tabsConfCiclos, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsConfCiclos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoPuntoAcumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPuntoAcumActionPerformed
        etiquetaNumPuntosAcum.setText(String.valueOf(
            Integer.parseInt(etiquetaNumPuntosAcum.getText()) + 1));
    }//GEN-LAST:event_btnNuevoPuntoAcumActionPerformed

    private void btnRestarPuntoAcumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarPuntoAcumActionPerformed
        if (Integer.parseInt(etiquetaNumPuntosAcum.getText()) > 0) {
            etiquetaNumPuntosAcum.setText(String.valueOf(
                Integer.parseInt(etiquetaNumPuntosAcum.getText()) - 1));
        }
    }//GEN-LAST:event_btnRestarPuntoAcumActionPerformed

    private void listaRutasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaRutasValueChanged
        Ruta ruta = rutas.get(listaRutas.getSelectedIndex());
        modeloCalles.clear();
        if (ruta.getCalles() != null) {
            for (int i = 0; i < ruta.getCalles().size(); i++) {
                modeloCalles.addElement(this.rutas.get(
                        listaRutas.getSelectedIndex()).getCalles().get(i).getNombre());
            }
        }
        reiniciarMenu();
    }//GEN-LAST:event_listaRutasValueChanged

    private void listaCallesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaCallesValueChanged
        if (listaCalles.getSelectedIndex() > -1) {
            reiniciarMenu();
            Calle calle = rutas.get(listaRutas.getSelectedIndex())
                    .getCalles().get(listaCalles.getSelectedIndex());
            if (calle.getPuntosAcum() != null) {
                etiquetaNumPuntosAcum.setText(String.valueOf(calle.getPuntosAcum().getNumeroPuntos()));
                campoTasaAcum.setText(calle.getPuntosAcum().getTasaAcumulacion().getCampo());
                campoTasaGen.setText(calle.getPuntosAcum().getTasaGeneracion().getCampo());
                int[] arraySemanal = calle.getPuntosAcum().getFactorSemanal();
                int[] arrayDiario = calle.getPuntosAcum().getFactorHora();

                for (int i = 0; i < arraySemanal.length; i++) {
                    sliderSemanal[i].setValue(arraySemanal[i]);
                }

                for (int i = 0; i < arrayDiario.length; i++) {
                    sliderDiario[i].setValue(arrayDiario[i]);
                }
            }
        }
    }//GEN-LAST:event_listaCallesValueChanged

    private void listaRutasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaRutasMouseClicked
        if (evt.getButton() == 3) {
            listaRutas.clearSelection();
            listaCalles.clearSelection();
            reiniciarMenu();
        }
    }//GEN-LAST:event_listaRutasMouseClicked

    private void listaCallesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaCallesMouseClicked
        if (evt.getButton() == 3) {
            listaCalles.clearSelection();
            reiniciarMenu();
        }
    }//GEN-LAST:event_listaCallesMouseClicked

    private void btnCrearPtoAcumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPtoAcumActionPerformed
        if (esValido()) { 
            if (listaRutas.getSelectedIndex() > -1 &&
                    listaCalles.getSelectedIndex() > -1) {
                int[] arraySemanal = new int[7];
                int[] arrayDiario = new int[24];

                for (int i = 0; i < sliderSemanal.length; i++) {
                    arraySemanal[i] = sliderSemanal[i].getValue();
                }

                for (int i = 0; i < sliderDiario.length; i++) {
                    arrayDiario[i] = sliderDiario[i].getValue();
                }

                PuntosAcumulacion puntosAcum;
                
                if (Distribucion.seriaDistEspecial(campoTasaGen.getText()))                 {
                    puntosAcum = new PuntosAcumulacion(
                            new Distribucion(campoTasaAcum.getText()),
                            new Distribucion(campoTasaGen.getText(), arraySemanal, arrayDiario),
                            arrayDiario, arraySemanal, Integer.parseInt(etiquetaNumPuntosAcum.getText())
                    );
                } else {
                    puntosAcum = new PuntosAcumulacion(
                            new Distribucion(campoTasaAcum.getText()),
                            new Distribucion(campoTasaGen.getText()), arrayDiario,
                            arraySemanal, Integer.parseInt(etiquetaNumPuntosAcum.getText()));   
                }

                rutas.get(listaRutas.getSelectedIndex()).getCalles()
                        .get(listaCalles.getSelectedIndex())
                        .setPuntosAcum(puntosAcum);
                UI.alerta("Puntos de acumulación añadidos correctamente");
            }
        }
    }//GEN-LAST:event_btnCrearPtoAcumActionPerformed

    private void btnEditarPtoAcumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPtoAcumActionPerformed
        if (esValido()) {
            if (listaRutas.getSelectedIndex() > -1
                    && listaCalles.getSelectedIndex() > -1) {
                PuntosAcumulacion puntosAcum = rutas.get(listaRutas.getSelectedIndex())
                        .getCalles().get(listaCalles.getSelectedIndex()).getPuntosAcum();
                puntosAcum.setNumeroPuntos(Integer.parseInt(etiquetaNumPuntosAcum.getText()));
                puntosAcum.setTasaAcumulacion(new Distribucion(campoTasaAcum.getText()));
                puntosAcum.setTasaGeneracion(new Distribucion(campoTasaGen.getText()));

                int[] arraySemanal = new int[7];
                int[] arrayDiario = new int[24];

                for (int i = 0; i < sliderSemanal.length; i++) {
                    arraySemanal[i] = sliderSemanal[i].getValue();
                }

                for (int i = 0; i < sliderDiario.length; i++) {
                    arrayDiario[i] = sliderDiario[i].getValue();
                }

                puntosAcum.setFactorSemanal(arraySemanal);
                puntosAcum.setFactorHora(arrayDiario);
                UI.alerta("Puntos de acumulación editados correctamente");
            }
        }
    }//GEN-LAST:event_btnEditarPtoAcumActionPerformed

    private void btnCancelarPtoAcumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPtoAcumActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        reiniciarMenu();
    }//GEN-LAST:event_btnCancelarPtoAcumActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarPtoAcum;
    private javax.swing.JButton btnCrearPtoAcum;
    private javax.swing.JButton btnEditarPtoAcum;
    private javax.swing.JButton btnNuevoPuntoAcum;
    private javax.swing.JButton btnRestarPuntoAcum;
    private javax.swing.JTextField campoTasaAcum;
    private javax.swing.JTextField campoTasaGen;
    private javax.swing.JLabel etiqueta10AM;
    private javax.swing.JLabel etiqueta10PM;
    private javax.swing.JLabel etiqueta11AM;
    private javax.swing.JLabel etiqueta11PM;
    private javax.swing.JLabel etiqueta12AM;
    private javax.swing.JLabel etiqueta12PM;
    private javax.swing.JLabel etiqueta1AM;
    private javax.swing.JLabel etiqueta1PM;
    private javax.swing.JLabel etiqueta2AM;
    private javax.swing.JLabel etiqueta2PM;
    private javax.swing.JLabel etiqueta3AM;
    private javax.swing.JLabel etiqueta3PM;
    private javax.swing.JLabel etiqueta4AM;
    private javax.swing.JLabel etiqueta4PM;
    private javax.swing.JLabel etiqueta5AM;
    private javax.swing.JLabel etiqueta5PM;
    private javax.swing.JLabel etiqueta6AM;
    private javax.swing.JLabel etiqueta6PM;
    private javax.swing.JLabel etiqueta7AM;
    private javax.swing.JLabel etiqueta7PM;
    private javax.swing.JLabel etiqueta8AM;
    private javax.swing.JLabel etiqueta8PM;
    private javax.swing.JLabel etiqueta9AM;
    private javax.swing.JLabel etiqueta9PM;
    private javax.swing.JLabel etiquetaCalles;
    private javax.swing.JLabel etiquetaCantPuntosAcum;
    private javax.swing.JLabel etiquetaCicloDiario;
    private javax.swing.JLabel etiquetaCicloSemanal;
    private javax.swing.JLabel etiquetaDoming;
    private javax.swing.JLabel etiquetaJueves;
    private javax.swing.JLabel etiquetaLunes;
    private javax.swing.JLabel etiquetaMartes;
    private javax.swing.JLabel etiquetaMiercoles;
    private javax.swing.JLabel etiquetaNumPuntosAcum;
    private javax.swing.JLabel etiquetaRutas;
    private javax.swing.JLabel etiquetaSabado;
    private javax.swing.JLabel etiquetaTasaAcum;
    private javax.swing.JLabel etiquetaTasaGen;
    private javax.swing.JLabel etiquetaViernes;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaCalles;
    private javax.swing.JList<String> listaRutas;
    private javax.swing.JSlider slider10AM;
    private javax.swing.JSlider slider10PM;
    private javax.swing.JSlider slider11AM;
    private javax.swing.JSlider slider11PM;
    private javax.swing.JSlider slider12AM;
    private javax.swing.JSlider slider12PM;
    private javax.swing.JSlider slider1AM;
    private javax.swing.JSlider slider1PM;
    private javax.swing.JSlider slider2AM;
    private javax.swing.JSlider slider2PM;
    private javax.swing.JSlider slider3AM;
    private javax.swing.JSlider slider3PM;
    private javax.swing.JSlider slider4AM;
    private javax.swing.JSlider slider4PM;
    private javax.swing.JSlider slider5AM;
    private javax.swing.JSlider slider5PM;
    private javax.swing.JSlider slider6AM;
    private javax.swing.JSlider slider6PM;
    private javax.swing.JSlider slider7AM;
    private javax.swing.JSlider slider7PM;
    private javax.swing.JSlider slider8AM;
    private javax.swing.JSlider slider8PM;
    private javax.swing.JSlider slider9AM;
    private javax.swing.JSlider slider9PM;
    private javax.swing.JSlider sliderDomingo;
    private javax.swing.JSlider sliderJueves;
    private javax.swing.JSlider sliderLunes;
    private javax.swing.JSlider sliderMartes;
    private javax.swing.JSlider sliderMiercoles;
    private javax.swing.JSlider sliderSabado;
    private javax.swing.JSlider sliderViernes;
    private javax.swing.JTabbedPane tabCicloDIario;
    private javax.swing.JTabbedPane tabsConfCiclos;
    // End of variables declaration//GEN-END:variables
}
