/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JFrame;

/**
 *
 * @author gtroncone
 */
public class MenuConfiguracion extends javax.swing.JFrame {

    private final UI interfaz;
    
    /**
     * Creates new form MenuConfiguracion
     * @param interfaz
     * @throws java.io.IOException
     */
    public MenuConfiguracion(UI interfaz) throws IOException {
        this.interfaz = interfaz;
        initComponents();
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaIntervaloASim = new javax.swing.JLabel();
        checkCompleto = new javax.swing.JCheckBox();
        dropHoraInicial = new javax.swing.JComboBox<>();
        etiquetaIntervaloA = new javax.swing.JLabel();
        dropHoraFinal = new javax.swing.JComboBox<>();
        etiquetaNumRepeticiones = new javax.swing.JLabel();
        etiquetaDigNumRepeticiones = new javax.swing.JLabel();
        btnNuevaRepeticion = new javax.swing.JButton();
        btnRemoverRepeticion = new javax.swing.JButton();
        etiquetaSalarioBarredores = new javax.swing.JLabel();
        campoSalarioBarredores = new javax.swing.JTextField();
        etiquetaSalarioEquipoRec = new javax.swing.JLabel();
        campoEquipoRec = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        etiquetaNumMecanicos = new javax.swing.JLabel();
        etiquetaDigNumMecanicos = new javax.swing.JLabel();
        btnNuevoMecanico = new javax.swing.JButton();
        btnRemoverMecanico = new javax.swing.JButton();
        etiquetaSalarioMecanicos = new javax.swing.JLabel();
        campoSalarioMecanicos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiquetaIntervaloASim.setText("Intervalo a Simular");

        checkCompleto.setText("Completo");

        dropHoraInicial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        etiquetaIntervaloA.setText("a");

        dropHoraFinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        etiquetaNumRepeticiones.setText("Número de Repeticiones");

        etiquetaDigNumRepeticiones.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaDigNumRepeticiones.setText("0");

        btnNuevaRepeticion.setText("+");
        btnNuevaRepeticion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaRepeticionActionPerformed(evt);
            }
        });

        btnRemoverRepeticion.setText("-");
        btnRemoverRepeticion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverRepeticionActionPerformed(evt);
            }
        });

        etiquetaSalarioBarredores.setText("Salario de Barredores");

        etiquetaSalarioEquipoRec.setText("Salario de Equipo de Recolección");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        etiquetaNumMecanicos.setText("Número de Mecánicos");

        etiquetaDigNumMecanicos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaDigNumMecanicos.setText("0");

        btnNuevoMecanico.setText("+");
        btnNuevoMecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoMecanicoActionPerformed(evt);
            }
        });

        btnRemoverMecanico.setText("-");
        btnRemoverMecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverMecanicoActionPerformed(evt);
            }
        });

        etiquetaSalarioMecanicos.setText("Salario de Mecánicos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnCancelar)
                .addGap(132, 132, 132))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaNumMecanicos)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiquetaIntervaloASim)
                                .addGap(18, 18, 18)
                                .addComponent(checkCompleto))
                            .addComponent(etiquetaNumRepeticiones)
                            .addComponent(etiquetaSalarioBarredores)
                            .addComponent(etiquetaSalarioEquipoRec)
                            .addComponent(etiquetaSalarioMecanicos))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dropHoraInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(etiquetaIntervaloA)
                                .addGap(18, 18, 18)
                                .addComponent(dropHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(campoSalarioMecanicos, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(etiquetaDigNumMecanicos, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnNuevoMecanico)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRemoverMecanico))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(campoEquipoRec, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(campoSalarioBarredores, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(etiquetaDigNumRepeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnNuevaRepeticion)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnRemoverRepeticion))))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaIntervaloASim)
                    .addComponent(checkCompleto)
                    .addComponent(dropHoraInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaIntervaloA)
                    .addComponent(dropHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNumRepeticiones)
                    .addComponent(etiquetaDigNumRepeticiones)
                    .addComponent(btnNuevaRepeticion)
                    .addComponent(btnRemoverRepeticion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaSalarioBarredores)
                    .addComponent(campoSalarioBarredores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaSalarioEquipoRec)
                    .addComponent(campoEquipoRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNumMecanicos)
                    .addComponent(etiquetaDigNumMecanicos)
                    .addComponent(btnNuevoMecanico)
                    .addComponent(btnRemoverMecanico))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaSalarioMecanicos)
                    .addComponent(campoSalarioMecanicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaRepeticionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaRepeticionActionPerformed
        etiquetaDigNumRepeticiones.setText(String.valueOf(
            Integer.parseInt(etiquetaDigNumRepeticiones.getText()) + 1));
    }//GEN-LAST:event_btnNuevaRepeticionActionPerformed

    private void btnRemoverRepeticionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverRepeticionActionPerformed
        if (Integer.parseInt(etiquetaDigNumRepeticiones.getText()) > 0) {
            etiquetaDigNumRepeticiones.setText(String.valueOf(
                Integer.parseInt(etiquetaDigNumRepeticiones.getText()) - 1));
        }
    }//GEN-LAST:event_btnRemoverRepeticionActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        //TODO: Reiniciar estado del componente
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNuevoMecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoMecanicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoMecanicoActionPerformed

    private void btnRemoverMecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverMecanicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoverMecanicoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevaRepeticion;
    private javax.swing.JButton btnNuevoMecanico;
    private javax.swing.JButton btnRemoverMecanico;
    private javax.swing.JButton btnRemoverRepeticion;
    private javax.swing.JTextField campoEquipoRec;
    private javax.swing.JTextField campoSalarioBarredores;
    private javax.swing.JTextField campoSalarioMecanicos;
    private javax.swing.JCheckBox checkCompleto;
    private javax.swing.JComboBox<String> dropHoraFinal;
    private javax.swing.JComboBox<String> dropHoraInicial;
    private javax.swing.JLabel etiquetaDigNumMecanicos;
    private javax.swing.JLabel etiquetaDigNumRepeticiones;
    private javax.swing.JLabel etiquetaIntervaloA;
    private javax.swing.JLabel etiquetaIntervaloASim;
    private javax.swing.JLabel etiquetaNumMecanicos;
    private javax.swing.JLabel etiquetaNumRepeticiones;
    private javax.swing.JLabel etiquetaSalarioBarredores;
    private javax.swing.JLabel etiquetaSalarioEquipoRec;
    private javax.swing.JLabel etiquetaSalarioMecanicos;
    // End of variables declaration//GEN-END:variables
}
